source "https://rubygems.org"

ruby "3.3.1"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "rack-cors"

# Background jobs
gem "sidekiq", "~> 7.1"
gem "redis", "~> 5.0"

# GraphQL
gem "graphql", "~> 2.1"

# Authentication
gem "jwt"
gem "bcrypt", "~> 3.1.7"

# API
gem "jbuilder"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
end

group :development do
  gem "spring"
  # gem "rubocop", require: false
  # gem "rubocop-rails", require: false
  # gem "rubocop-rspec", require: false
end

group :test do
  gem "database_cleaner-active_record"
  gem "simplecov", require: false
  gem "webmock"
  gem "vcr"
end
gem "graphql-rails_logger", "~> 1.2"

gem "neighbor", "~> 0.5.2"

gem "omniauth", "~> 2.1"
gem "omniauth-github", "~> 2.0"
gem "omniauth-rails_csrf_protection", "~> 1.0"
